import type { Metadata } from "next";
import {Josefin_Sans} from "next/font/google"
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";
import ChatIcon from "./components/ChatIcon";

const josefinSans = Josefin_Sans({subsets :['latin'],
  weight:['100','300','400']
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${josefinSans.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
        <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#000000",
                color: "#ffffff",
              },
            }}
          />
          <ChatIcon/>
      </body>
    </html>
  );
}
